// Auto-generated by contract deployment script
// Do not edit manually - this file is overwritten on each deployment

export const SPINMINT_NFT_ADDRESS = "0x0000000000000000000000000000000000000000" as const

export const CHAIN_CONFIG = {
  baseSepolia: {
    id: 84532,
    name: "Base Sepolia",
    rpcUrl: "https://sepolia.base.org",
    blockExplorer: "https://sepolia.basescan.org",
    faucet: "https://www.coinbase.com/faucets/base-ethereum-sepolia-faucet",
  },
  base: {
    id: 8453,
    name: "Base",
    rpcUrl: "https://mainnet.base.org",
    blockExplorer: "https://basescan.org",
    faucet: null,
  },
} as const

export const DEFAULT_CHAIN_ID = 84532 // Base Sepolia
