import { ethers } from "hardhat"
import { writeFileSync } from "fs"
import { join } from "path"

async function main() {
  console.log("🚀 Deploying SpinMintNFT contract to Base Sepolia...")

  // Get the contract factory
  const SpinMintNFT = await ethers.getContractFactory("SpinMintNFT")

  // Deploy the contract
  const spinMintNFT = await SpinMintNFT.deploy()
  await spinMintNFT.waitForDeployment()

  const contractAddress = await spinMintNFT.getAddress()

  console.log("✅ SpinMintNFT deployed to:", contractAddress)
  console.log("🔗 View on BaseScan:", `https://sepolia.basescan.org/address/${contractAddress}`)

  // Write the contract address to the frontend constants file
  const constantsPath = join(__dirname, "../../my-minikit-app/utils/constants.ts")

  const constantsContent = `// Auto-generated by contract deployment script
// Do not edit manually - this file is overwritten on each deployment

export const SPINMINT_NFT_ADDRESS = "${contractAddress}" as const;

export const CHAIN_CONFIG = {
  baseSepolia: {
    id: 84532,
    name: "Base Sepolia",
    rpcUrl: "https://sepolia.base.org",
    blockExplorer: "https://sepolia.basescan.org",
    faucet: "https://www.coinbase.com/faucets/base-ethereum-sepolia-faucet"
  },
  base: {
    id: 8453,
    name: "Base",
    rpcUrl: "https://mainnet.base.org", 
    blockExplorer: "https://basescan.org",
    faucet: null
  }
} as const;

export const DEFAULT_CHAIN_ID = 84532; // Base Sepolia
`

  try {
    writeFileSync(constantsPath, constantsContent)
    console.log("📝 Contract address written to:", constantsPath)
  } catch (error) {
    console.warn("⚠️  Could not write to constants file:", error)
    console.log("📋 Please manually update SPINMINT_NFT_ADDRESS to:", contractAddress)
  }

  // Verify contract deployment
  console.log("\n🔍 Verifying deployment...")
  const name = await spinMintNFT.name()
  const symbol = await spinMintNFT.symbol()
  const totalSupply = await spinMintNFT.totalSupply()

  console.log("Contract Name:", name)
  console.log("Contract Symbol:", symbol)
  console.log("Total Supply:", totalSupply.toString())

  console.log("\n🎉 Deployment completed successfully!")
  console.log("Next steps:")
  console.log("1. Update your .env.local with the deployed contract address")
  console.log("2. Deploy your frontend to Vercel")
  console.log("3. Test minting functionality")
}

main()
  .then(() => process.exit(0))
  .catch((error) => {
    console.error("❌ Deployment failed:", error)
    process.exit(1)
  })
